version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    container_name: tienda_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: api_postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: usuarios_db
    restart: unless-stopped

  apiusuarios:
    build: ./apiusuarios
    container_name: apiusuarios
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./apiusuarios:/app
    environment:
      - NODE_ENV=development
    command: npm start
    depends_on:
      - postgres
      - mongodb

volumes:
  mongo_data:
  pg_data:
